In [72]:
import numpy as np
import pandas as pd

In [90]:
m=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
md=pd.DataFrame(m)
mdc=pd.DataFrame(m)
mdi=pd.DataFrame(m)
print(m)
md

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


0   1   2   3
0   1   2   3   4
1   5   6   7   8
2   9  10  11  12
3  13  14  15  16

In [8]:
m[0][3]

4

In [9]:
m[0,3]

4

In [9]:
m[0:1]

array([[1, 2, 3, 4]])

In [11]:
m[:,:]

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [32]:
m[1:2,0:4]

array([[5, 6, 7, 8]])

In [10]:
m[1:3]

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [46]:
m[0:2][0:1]

array([[1, 2, 3, 4]])

In [35]:
m[0,2]

3

In [36]:
m[0][2]

3

In [34]:
x=[0,3]
y=[1,2]
m[x,y]

array([ 2, 15])

In [91]:
md

0   1   2   3
0   1   2   3   4
1   5   6   7   8
2   9  10  11  12
3  13  14  15  16

In [92]:
md[2:3]

0   1   2   3
2  9  10  11  12

In [93]:
mdc.columns={"a","b","c","d"}

In [95]:
mdc[1:3][0:1]

a  b  c  d
1  5  6  7  8

In [98]:
f=[1,2]
ff=["c","d"]
mdc[0:2][["a","c"]]

a  c
0  1  3
1  5  7

In [100]:
mdc[0,"a"]

KeyError: (0, 'a')

In [102]:
md[0][2]

9

In [104]:
mdc[0]["c"]

KeyError: 0

In [79]:
md[0][2]

KeyError: 0

In [105]:
mdi

0   1   2   3
0   1   2   3   4
1   5   6   7   8
2   9  10  11  12
3  13  14  15  16

In [156]:
mdi.index=["x","y","z","t"]

In [157]:
mdi

0   1   2   3
x   1   2   3   4
y   5   6   7   8
z   9  10  11  12
t  13  14  15  16

In [108]:
mdi[0][2]

9

In [109]:
mdi["z"][2]

KeyError: 'z'

In [110]:
md

0   1   2   3
0   1   2   3   4
1   5   6   7   8
2   9  10  11  12
3  13  14  15  16

In [86]:
md[0,2]

InvalidIndexError: (0, 2)

InvalidIndexError: ('a', 2)

In [111]:
md

0   1   2   3
0   1   2   3   4
1   5   6   7   8
2   9  10  11  12
3  13  14  15  16

In [161]:
mdc

a   b   c   d
0   1   2   3   4
1   5   6   7   8
2   9  10  11  12
3  13  14  15  16

In [153]:
mdi

0   1   2   3
z   1   2   3   4
y   5   6   7   8
x   9  10  11  12
t  13  14  15  16

In [120]:
md[0][0]

1

In [128]:
md[2]

0     3
1     7
2    11
3    15
Name: 2, dtype: int64

In [166]:
mdc.loc[:,"a":"c"]


a   b   c
0   1   2   3
1   5   6   7
2   9  10  11
3  13  14  15

In [196]:
mdi.index=["x","y","z","t"]
mdi

0   1   2   3
x   1   2   3   4
y   5   6   7   8
z   9  10  11  12
t  13  14  15  16

In [202]:
f=["a","b"]
mdi["x":"z"][2:3]

0   1   2   3
z  9  10  11  12