# Değişkne Standardizasyonu / Veri standardizasyonu

standartşaltırmada verinin öztütü bozlmaz

ancak dönüştürmede taşıdığı bilgi değişir yada temsili değişir

In [4]:
import numpy as np
import pandas as pd
V1 = np.array([1,3,6,5,7])
V2 = np.array([7,7,5,8,12])
V3 = np.array([6,12,5,6,14])
df=pd.DataFrame({"V1":V1,
                "V2":V2,
                "V3":V3})
df=df.astype("float64")
print(df.info())
df

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   V1      5 non-null      float64
 1   V2      5 non-null      float64
 2   V3      5 non-null      float64
dtypes: float64(3)
memory usage: 248.0 bytes
None


V1    V2    V3
0  1.0   7.0   6.0
1  3.0   7.0  12.0
2  6.0   5.0   5.0
3  5.0   8.0   6.0
4  7.0  12.0  14.0

## Standardizasyon

In [5]:
from sklearn import preprocessing

In [6]:
preprocessing.scale(df)
#şu an tüm değişkenleri stadartlaştırdı hepisni aynı aynda yaptığı içn bşrbşrlerşyle ilşkielri  bozulmadı

array([[-1.57841037, -0.34554737, -0.70920814],
       [-0.64993368, -0.34554737,  0.92742603],
       [ 0.74278135, -1.2094158 , -0.98198051],
       [ 0.27854301,  0.08638684, -0.70920814],
       [ 1.2070197 ,  1.81412369,  1.47297076]])

## Normalizasyon

In [7]:
preprocessing.normalize(df)
#tüm değişkne 0 1 arasında olacak şekilde ayralanır

array([[0.10783277, 0.75482941, 0.64699664],
       [0.21107926, 0.49251828, 0.84431705],
       [0.64699664, 0.53916387, 0.53916387],
       [0.4472136 , 0.71554175, 0.53665631],
       [0.35491409, 0.60842415, 0.70982818]])

In [18]:
# yukarıda 0 1 arasında olacak şekilde ayarlandı ancak max min değer,ni kendimizde belileyebiliriz
# #hatta bu değerler veri setimizin içinde olmayan değerler de olabilir
scaler=preprocessing.MinMaxScaler(feature_range=(100,200))  

In [20]:
scaler.fit_transform(df)
#normalde biz bu fit_transform fonksiyonunu direkt yukarıdaki şlemin sonuna da ekleyenilirdik.
# burada scaler değişkenine atadık onu bir dönüştürücü haline getirdik sonra tranform ile df üzerine uyguladık:))
#direkt ekelenrek yapıldığı haşide bi alt satırda :)

array([[100.        , 128.57142857, 111.11111111],
       [133.33333333, 128.57142857, 177.77777778],
       [183.33333333, 100.        , 100.        ],
       [166.66666667, 142.85714286, 111.11111111],
       [200.        , 200.        , 200.        ]])

In [21]:
preprocessing.MinMaxScaler(feature_range=(100,200)).fit_transform(df)

array([[100.        , 128.57142857, 111.11111111],
       [133.33333333, 128.57142857, 177.77777778],
       [183.33333333, 100.        , 100.        ],
       [166.66666667, 142.85714286, 111.11111111],
       [200.        , 200.        , 200.        ]])