# DEğişkne Standartlaştırmama / Değişken Dönüşümü

* Veri standartlaştırmada karşılaştırılabilirliğini korururuz
* Dönüşümde ise tamamen dönüştürürüz
* standartlaştımada varyasyon korunur ölçek değişir
* dönüşümde ise ölçek bazen korunur bazen bozulur. çünkü böyle bir kaygımız yok 

In [4]:
import numpy as np
import pandas as pd
V1 = np.array([1,3,6,5,7])
V2 = np.array([7,7,5,8,12])
V3 = np.array([6,12,5,6,14])
df=pd.DataFrame({"V1":V1,
                "V2":V2,
                "V3":V3})
df=df.astype("float64")
print(df.info())
df

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   V1      5 non-null      float64
 1   V2      5 non-null      float64
 2   V3      5 non-null      float64
dtypes: float64(3)
memory usage: 248.0 bytes
None


V1    V2    V3
0  1.0   7.0   6.0
1  3.0   7.0  12.0
2  6.0   5.0   5.0
3  5.0   8.0   6.0
4  7.0  12.0  14.0

In [3]:
# standartlaştıma için scale kullanılır

In [14]:
vars=list(df)

In [48]:
from sklearn import preprocessing
dff=preprocessing.scale(df) # ort = 0 std = 1 olacak şekilde standartlaştırma yaptık
dff

array([[-1.57841037, -0.34554737, -0.70920814],
       [-0.64993368, -0.34554737,  0.92742603],
       [ 0.74278135, -1.2094158 , -0.98198051],
       [ 0.27854301,  0.08638684, -0.70920814],
       [ 1.2070197 ,  1.81412369,  1.47297076]])

In [24]:
dff.std()

1.0

## Normalizasyon

0 1 arsına dönüştürülür

In [45]:
preprocessing.normalize(df)

array([[0.10783277, 0.75482941, 0.64699664],
       [0.21107926, 0.49251828, 0.84431705],
       [0.64699664, 0.53916387, 0.53916387],
       [0.4472136 , 0.71554175, 0.53665631],
       [0.35491409, 0.60842415, 0.70982818]])

## Min Max Dönüşümü
isediğmiz iki değer arasına dönüştürme
burada donuşturucu kullanırız

In [49]:
donusturucu=preprocessing.MinMaxScaler(feature_range=(0,100))
donusturucu.fit_transform(df)

array([[  0.        ,  28.57142857,  11.11111111],
       [ 33.33333333,  28.57142857,  77.77777778],
       [ 83.33333333,   0.        ,   0.        ],
       [ 66.66666667,  42.85714286,  11.11111111],
       [100.        , 100.        , 100.        ]])

Buraya kadar değişkenlerin varyans yapısı korundu ama ölçekleri değişti
daha geniiş daha yayvan oldu ama kendi aralırındaki o yayilim korundu çünkü bir işlem hepsine uygulandı

## Binary Dönüşümü
burada eşik değer belirleyip n-binary ddönüşüm yapıyoruz
yani eşik değerli  0 1 dönüşümü

In [51]:
donusturucu_bin=preprocessing.Binarizer(threshold=5).fit(df)
donusturucu_bin.transform(df)

array([[0., 1., 1.],
       [0., 1., 1.],
       [1., 0., 0.],
       [0., 1., 1.],
       [1., 1., 1.]])

## 0 1 dönüşümü
burada maksat sadece değişkenş numerik hale getrimek

In [49]:
import seaborn as sns
df_titanic=sns.load_dataset("titanic")
df_titanic.head()


survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [21]:
df_titanic["sex"]=df_titanic["sex"].astype("category") #cat sadece kategorşk ile çalıştığı içi dönüşüm yaptık
df_titanic["new_sex"]=df_titanic["sex"].cat.codes
#bir yüntem daha var

In [20]:
label01=preprocessing.LabelEncoder()
df_titanic["newest_sex"]=label01.fit_transform(df_titanic["sex"])
df_titanic

survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
0           0       3    male  22.0      1      0   7.2500        S   Third   
1           1       1  female  38.0      1      0  71.2833        C   First   
2           1       3  female  26.0      0      0   7.9250        S   Third   
3           1       1  female  35.0      1      0  53.1000        S   First   
4           0       3    male  35.0      0      0   8.0500        S   Third   
..        ...     ...     ...   ...    ...    ...      ...      ...     ...   
886         0       2    male  27.0      0      0  13.0000        S  Second   
887         1       1  female  19.0      0      0  30.0000        S   First   
888         0       3  female   NaN      1      2  23.4500        S   Third   
889         1       1    male  26.0      0      0  30.0000        C   First   
890         0       3    male  32.0      0      0   7.7500        Q   Third   

       who  adult_male deck  embark_town alive  alone  new_sex  newest_sex  
0      man        True  NaN  Southampton    no  False        1           1  
1    woman       False    C    Cherbourg   yes  False        0           0  
2    woman       False  NaN  Southampton   yes   True        0           0  
3    woman       False    C  Southampton   yes  False        0           0  
4      man        True  NaN  Southampton    no   True        1           1  
..     ...         ...  ...          ...   ...    ...      ...         ...  
886    man        True  NaN  Southampton    no   True        1           1  
887  woman       False    B  Southampton   yes   True        0           0  
888  woman       False  NaN  Southampton    no  False        0           0  
889    man        True    C    Cherbourg   yes   True        1           1  
890    man        True  NaN   Queenstown    no   True        1           1  

[891 rows x 17 columns]

## 1 diğerlei 0
belirli değişkemin etkisi daha fdazla olduğunu fark ettiğimizde belirli değiken yada değişkenlerşn 1 diğerlerin sıfır olarak değiştirilmeisdir

In [52]:
tip=sns.load_dataset("tips")
tip.head(20)

total_bill   tip     sex smoker  day    time  size
0        16.99  1.01  Female     No  Sun  Dinner     2
1        10.34  1.66    Male     No  Sun  Dinner     3
2        21.01  3.50    Male     No  Sun  Dinner     3
3        23.68  3.31    Male     No  Sun  Dinner     2
4        24.59  3.61  Female     No  Sun  Dinner     4
5        25.29  4.71    Male     No  Sun  Dinner     4
6         8.77  2.00    Male     No  Sun  Dinner     2
7        26.88  3.12    Male     No  Sun  Dinner     4
8        15.04  1.96    Male     No  Sun  Dinner     2
9        14.78  3.23    Male     No  Sun  Dinner     2
10       10.27  1.71    Male     No  Sun  Dinner     2
11       35.26  5.00  Female     No  Sun  Dinner     4
12       15.42  1.57    Male     No  Sun  Dinner     2
13       18.43  3.00    Male     No  Sun  Dinner     4
14       14.83  3.02  Female     No  Sun  Dinner     2
15       21.58  3.92    Male     No  Sun  Dinner     2
16       10.33  1.67  Female     No  Sun  Dinner     3
17       16.29  3.71    Male     No  Sun  Dinner     3
18       16.97  3.50  Female     No  Sun  Dinner     3
19       20.65  3.35    Male     No  Sat  Dinner     3

In [38]:
tip["new_day_label"]=np.where(tip["day"].str.contains("Sun"),1,0)
tip

total_bill   tip     sex smoker   day    time  size  new_day_label
0         16.99  1.01  Female     No   Sun  Dinner     2              1
1         10.34  1.66    Male     No   Sun  Dinner     3              1
2         21.01  3.50    Male     No   Sun  Dinner     3              1
3         23.68  3.31    Male     No   Sun  Dinner     2              1
4         24.59  3.61  Female     No   Sun  Dinner     4              1
..          ...   ...     ...    ...   ...     ...   ...            ...
239       29.03  5.92    Male     No   Sat  Dinner     3              0
240       27.18  2.00  Female    Yes   Sat  Dinner     2              0
241       22.67  2.00    Male    Yes   Sat  Dinner     2              0
242       17.82  1.75    Male     No   Sat  Dinner     2              0
243       18.78  3.00  Female     No  Thur  Dinner     2              0

[244 rows x 8 columns]

## Çok değişkenli Dönüşüm

In [50]:
label=preprocessing.LabelEncoder()
tip["newst_day"]=label.fit_transform(tip["day"])
tip
#burada sınıfları 1,2,3 diye sınıflandırır ama dah aöncede bahsettiğimiz gibi bu durumda
#sınıfları bir sıray sıraya koymuşuz üstğnlüj belirtmişiz gibi olur 
# # bu yüzden kategorik değişkenş numeriğe dönüştürüken one hot dönüşümünü kullanmak daha mantıklı olur 

total_bill   tip     sex smoker   day    time  size  newst_day
0         16.99  1.01  Female     No   Sun  Dinner     2          2
1         10.34  1.66    Male     No   Sun  Dinner     3          2
2         21.01  3.50    Male     No   Sun  Dinner     3          2
3         23.68  3.31    Male     No   Sun  Dinner     2          2
4         24.59  3.61  Female     No   Sun  Dinner     4          2
..          ...   ...     ...    ...   ...     ...   ...        ...
239       29.03  5.92    Male     No   Sat  Dinner     3          1
240       27.18  2.00  Female    Yes   Sat  Dinner     2          1
241       22.67  2.00    Male    Yes   Sat  Dinner     2          1
242       17.82  1.75    Male     No   Sat  Dinner     2          1
243       18.78  3.00  Female     No  Thur  Dinner     2          3

[244 rows x 8 columns]

## One Hot Dönüşümü

In [46]:
pd.get_dummies(tip, columns=["day"], prefix=["day"])
# bu one hot'ı eğer ki iki sınıflı bir değişken için kulllanırsan saçma olur. buna da dummy değişken tuzağı denilir

total_bill   tip     sex smoker    time  size  day_Thur  day_Fri  \
0         16.99  1.01  Female     No  Dinner     2         0        0   
1         10.34  1.66    Male     No  Dinner     3         0        0   
2         21.01  3.50    Male     No  Dinner     3         0        0   
3         23.68  3.31    Male     No  Dinner     2         0        0   
4         24.59  3.61  Female     No  Dinner     4         0        0   
..          ...   ...     ...    ...     ...   ...       ...      ...   
239       29.03  5.92    Male     No  Dinner     3         0        0   
240       27.18  2.00  Female    Yes  Dinner     2         0        0   
241       22.67  2.00    Male    Yes  Dinner     2         0        0   
242       17.82  1.75    Male     No  Dinner     2         0        0   
243       18.78  3.00  Female     No  Dinner     2         1        0   

     day_Sat  day_Sun  
0          0        1  
1          0        1  
2          0        1  
3          0        1  
4          0        1  
..       ...      ...  
239        1        0  
240        1        0  
241        1        0  
242        1        0  
243        0        0  

[244 rows x 10 columns]

## Sürekli DEğikeni Kategpriğe Çevirme

In [54]:
tip.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [62]:
df_tip=tip.select_dtypes(include=["float64","int64"])
label_tip=preprocessing.KBinsDiscretizer(n_bins=[3,2,2], encode="ordinal", strategy="quantile" ).fit(df_tip)
label_tip.transform(df_tip)[0:10]

array([[1., 0., 1.],
       [0., 0., 1.],
       [1., 1., 1.],
       [2., 1., 1.],
       [2., 1., 1.],
       [2., 1., 1.],
       [0., 0., 1.],
       [2., 1., 1.],
       [1., 0., 1.],
       [0., 1., 1.]])

In [63]:
# normald sürekliden kategoriğe dönüştürmek pekte mantıklı bir dönüşüm değildir

## İndex Dönüşümleri

In [65]:
tip.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [66]:
tip["new"]=tip.index

In [68]:
tip.index=tip["new"]*10
tip.head()

total_bill   tip     sex smoker  day    time  size  new
new                                                         
0         16.99  1.01  Female     No  Sun  Dinner     2    0
10        10.34  1.66    Male     No  Sun  Dinner     3    1
20        21.01  3.50    Male     No  Sun  Dinner     3    2
30        23.68  3.31    Male     No  Sun  Dinner     2    3
40        24.59  3.61  Female     No  Sun  Dinner     4    4