In [1]:
import numpy as np

In [2]:
np.random.randint(5,10,size=10)

array([7, 6, 7, 5, 5, 8, 9, 9, 6, 7])

In [3]:
np.random.randint(5,10,10) # aynı şey fark etmez size=10 yada direjkt 10 yazmışsın aynı

array([5, 8, 7, 5, 6, 8, 9, 6, 7, 5])

In [6]:
np.random.randint(10,size=10)#şimdi burada başlangıç değerini boş bıraktık isteği yerden başlasın diye 
#ancak size yazmassak iki değer verdik sanır ve hat veririr. peki ya tek değer verirsen

array([5, 6, 6, 5, 2, 9, 6, 2, 3, 1])

In [24]:
np.random.randint(10) #tek sayı yazdırır

4

# array 
* ndim
* shape
* size
* dtype 

In [37]:
a=np.random.randint(5,size=5)
a

array([2, 2, 2, 0, 4])

In [38]:
a.ndim

1

In [39]:
a.shape

(5,)

In [32]:
a.size

5

In [40]:
a.dtype

dtype('int64')

In [41]:
b=np.random.randint(1,5,(2,2))
b

array([[4, 3],
       [4, 1]])

In [44]:
b.ndim

2

In [45]:
b.shape

(2, 2)

In [46]:
b.size

4

In [47]:
b.dtype

dtype('int64')

In [50]:
c=np.full((3,2),'a')
c

array([['a', 'a'],
       ['a', 'a'],
       ['a', 'a']], dtype='<U1')

In [51]:
c.dtype

dtype('<U1')

In [52]:
c.size

6

In [61]:
np.array([1,3,2,5,"e"]) # arraya sadece tek boyu verebiliyormuşuz :))

array(['1', '3', '2', '5', 'e'], dtype='<U21')

In [62]:
d=[1,"a"],[2,"b"],[3,"c"]

In [63]:
d.ndim #ops hata çünkü bu metodları çalıştırabilmek için nnumpy tipinde olmalı objesi olmalı
#yukarıda oluşturduğumuz nprmal matrisdi
#bu yüzden diğer orneklerin tümünde numpy metodları ile matrisler arraylar oluşturduk

AttributeError: 'tuple' object has no attribute 'ndim'