## concatenate([],axis) function
iki yada üç arrayi birleştirebilirsin :))
not: python'da matris oluşturuken dışada bir[] konuru mesala iki boyutlu 2:2 lik a=[[ 1,2 ],[ 3,4 ]] şeklidne yazılı
axis=eksen tipini belli eder 0=satir, 1=sutun --> yani 1=ikisini alt alta koy, 0=yan yana koy

In [31]:
import numpy as np
a=[1,2,3,4]
b=[5,6,7]
c=[8,9,10]
np.concatenate([a,b,c],0)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [23]:
m=np.array([[[1,2,3,4],[5,6,7,9],[10,11,12,14]]],dtype="int")
m2=np.array([[[12,13,14,12],[3,4,5,3],[3,6,4,7]]])

In [34]:
m12=np.concatenate([m,m2],axis=0)
m12

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  9],
        [10, 11, 12, 14]],

       [[12, 13, 14, 12],
        [ 3,  4,  5,  3],
        [ 3,  6,  4,  7]]])

In [33]:
m13=np.concatenate([m,m2],axis=0)
m13

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  9],
        [10, 11, 12, 14]],

       [[12, 13, 14, 12],
        [ 3,  4,  5,  3],
        [ 3,  6,  4,  7]]])