# beş foksiyon
zeros()
ones()
full()
arange()
linspace()
random.normal()
random.randint()

In [1]:
import numpy as np

#### zeros()

In [2]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [3]:
np.zeros(7,dtype='int')

array([0, 0, 0, 0, 0, 0, 0])

In [4]:
np.zeros((2,2),dtype="int")

array([[0, 0],
       [0, 0]])

#### ones()

In [5]:
np.ones((2,3),dtype="str")

array([['1', '1', '1'],
       ['1', '1', '1']], dtype='<U1')

#### full()

In [6]:
np.full(5,4)

array([4, 4, 4, 4, 4])

In [7]:
np.full((2,2),'N')

array([['N', 'N'],
       ['N', 'N']], dtype='<U1')

#### arange()

In [8]:
np.arange(0,10,1)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.arange(100,0,-1)

array([100,  99,  98,  97,  96,  95,  94,  93,  92,  91,  90,  89,  88,
        87,  86,  85,  84,  83,  82,  81,  80,  79,  78,  77,  76,  75,
        74,  73,  72,  71,  70,  69,  68,  67,  66,  65,  64,  63,  62,
        61,  60,  59,  58,  57,  56,  55,  54,  53,  52,  51,  50,  49,
        48,  47,  46,  45,  44,  43,  42,  41,  40,  39,  38,  37,  36,
        35,  34,  33,  32,  31,  30,  29,  28,  27,  26,  25,  24,  23,
        22,  21,  20,  19,  18,  17,  16,  15,  14,  13,  12,  11,  10,
         9,   8,   7,   6,   5,   4,   3,   2,   1])

In [10]:
np.arange(1.0,2,0.1,dtype="float")

array([1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9])

In [11]:
np.arange(1.0,2,0.1)

array([1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9])

#### linspace()
iki değeer arasında belirli sayıda eleman oluşturur

In [14]:
np.linspace(100,0,5)

array([100.,  75.,  50.,  25.,   0.])

In [15]:
np.linspace(0,15,10,dtype="int")

array([ 0,  1,  3,  5,  6,  8, 10, 11, 13, 15])

In [16]:
np.linspace(0,3,5,dtype="int")

array([0, 0, 1, 2, 3])

In [17]:
np.linspace(10,20,5,(2,2),dtype="int") #boyutu sallamadı :))

array([10, 12, 15, 17, 20])

#### random.normal()
random.normal(ort,std sap,boyut)

In [23]:
np.random.normal(10,3,(2,2)) #hocamburada data type belirliyemiyorsun. mantıken belirli bir stdsapmaya ve orta uygun olcak mecburen float olur

array([[ 7.88940385, 12.65874622],
       [17.14481545, 10.74707582]])

In [22]:
np.random.normal(2,0,(3,3)) 

array([[2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.]])

#### random.randint()
random belirli aralıklarda int sayı üretir :))

In [24]:
np.random.randint(10,100,(5,5))

array([[76, 11, 38, 16, 72],
       [14, 92, 61, 65, 11],
       [89, 47, 37, 70, 83],
       [75, 76, 90, 25, 19],
       [11, 73, 96, 58, 48]])

In [28]:
np.random.randint(0,1,(2,2))

array([[0, 0],
       [0, 0]])

In [31]:
np.random.randint(-5,-3,2)#low> high olamaz orneğin random.randint(5,2,(2,2)) olamz 5>2

array([-5, -5])