## Fancy Index
mesala öreneğin :))
bir arraydan belirli indislerdeki elemanları çekip yeni bir array oluşturmak istiyorus 
bunu kolaylıkla yapmayı sağlan işem fancy index. direkt bu isimli nübir şey kullanmıyoruz arka gerçeklerşn olay, bu mantık 
fancy index olyor 


In [2]:
import numpy as np
arr=np.linspace(5,15,10,dtype="int")
arr

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 15])

In [7]:
[arr[3],arr[5],arr[7]] #normal way

[8, 10, 12]

In [8]:
new_indis=[3,5,7]
arr[new_indis]

array([ 8, 10, 12])

In [10]:
array=np.random.randint(100,size=10)
array

array([72, 31, 38,  3, 83, 43, 19, 20, 46, 84])

In [12]:
indis=[1,5,9]
array[indis]

array([31, 43, 84])

yukarıda tek boyutlıu bir arrayden isteğimiz ,ndisler,n, alrak tek booyutlu  başka array oluşturduk. istersek
tek boyuttan iki boyutluda oluşturabiliriz

In [17]:
index2=[[0,1],[8,9]]
matris=array[index2]
matris

array([[72, 31],
       [46, 84]])

In [18]:
print(np.shape(matris))

(2, 2)


mantık şu normalde bir arrayden isteğin indisdeki elemaları seçip isteğin yere boyuta atayabilirsin değil mi?

sonuçta bşr değer elde attin ve isteğini yaparsın. burada seseçip sıralama işlemini beraber yapıyor. seçeiğin indisleri yazıyorsun(seçme)

onları isteğin şekşldeki arraya koyuyorsun(sıralama) sonra array_isme[secme_sırala_arrayi] dediği zaman hem seçip hem sıralamış oloyur. 

ez cümle önce seçip sırala işlemini dişarıda yapıyorsun sonra arrayin içerisinde çalıştırıyorsun 

### matris işlemleri



In [27]:
m=np.arange(1,10,1).reshape(3,3)
m

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

matristen matrise

In [25]:
index_r=[[0,0],[2,2]]
index_c=[[0,2],[0,2]]
m[index_r,index_c]

array([[1, 3],
       [7, 9]])

matristen array a

In [29]:
index_r=[0,1,2]
index_c=[0,1,2]
m[index_r,index_c]

array([1, 5, 9])

yine aynı m antık istediklerimizi seçip isteğimiz şekler getirdik en sonda arrayin içine yaip tamamladık :==

### Fancy ve basit index 

In [30]:
m

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [35]:
m[1,[0,2]] #satirdan birinciyiseç, sutundan 0 ve ikiyiseç array olarak yaz

array([4, 6])

In [37]:
in_r=[0,2]
m[in_r,1]

array([2, 8])

### Fancy ve slice

In [38]:
m[0:,[0,2]]

array([[1, 3],
       [4, 6],
       [7, 9]])

bir tane de örenek yapalım. submatris mantığını da kullandığımız

In [40]:
orn=np.arange(1,37,1).reshape(6,6)
orn

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])

In [65]:
i=[1,2,3,4]
orn[i,i]=0
orn #geç oldu ama temiz oldu :))

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  0,  9, 10, 11, 12],
       [13, 14,  0, 16, 17, 18],
       [19, 20, 21,  0, 23, 24],
       [25, 26, 27, 28,  0, 30],
       [31, 32, 33, 34, 35, 36]])