## normalde fonkssiyonlarla yapılan işlemleri matematiksel operatorlerle yapmak mümkün 

In [2]:
import numpy as np
m=np.arange(1,10,1,dtype="int").reshape(3,3)
m

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

**<**      **less() function**

In [9]:
m[m<5]


array([1, 2, 3, 4])

In [10]:
np.less(m,5)

array([[ True,  True,  True],
       [ True, False, False],
       [False, False, False]])

In [11]:
m*10

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [12]:
m

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
m/10

array([[0.1, 0.2, 0.3],
       [0.4, 0.5, 0.6],
       [0.7, 0.8, 0.9]])

In [14]:
m/10+1

array([[1.1, 1.2, 1.3],
       [1.4, 1.5, 1.6],
       [1.7, 1.8, 1.9]])

In [15]:
m**2

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [16]:
m[m%2!=0]

array([1, 3, 5, 7, 9])