In [1]:
import numpy as np
array=np.arange(11,20,1).reshape(3,3)
array

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

#### **and or kullanımı**

In [2]:
array[(array%2==0) & (array%16!=0)]

array([12, 14, 18])

In [4]:
array[(array%2==0) | (array%5==0)]

array([12, 14, 15, 16, 18])

In [9]:
b=array<19
b

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True, False]])

In [12]:
array[array%2==0] = -1
array

array([[11, -1, 13],
       [-1, 15, -1],
       [17, -1, 19]])

In [16]:
arr=np.array([[1,2],[3,4],[5,6],[7,8]])
arr
x=arr%2==0
y=arr%2!=0
t=np.array([arr[x],arr[y]]).reshape(2,4)
t #💃🏻😅

array([[2, 4, 6, 8],
       [1, 3, 5, 7]])