# reshape(row,column) method
vetktorden matrise, matristen vektore. hatta vektorden matrise vektor ozelliği korunarak çevirilebilir. ve sadece 9.99 ₺ şaka şaka :))
çalıştırmak için iki yötem var 
* array_ismi.reshape((new_shape))
* numpy.reshape(array_isme,(new_shape))
eğer array numpy array ise iki yöntemlde çalışır. değilse sadece numpy.reshape şeklinde çalışır.
birde shape için -1 yazabilirsin bu size i numpy'a bırakmak olur. 

In [6]:
import numpy as np

## from array to matris

In [7]:
a=np.array([1,2,3,4,5,6,7,8,9]) #vektor özelliğini  bozmadan matrise .çeviricez 
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
a=a.reshape((1,9)) #9 elemalı listeyi bir row dokuz column olarak iki boyutlu oldu

In [8]:
a.ndim

1

In [9]:
a.shape

(9,)

In [10]:
a.reshape((3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
a.ndim #ama kalıcı değişiklik yapmdaı çünkü atamadık :))

1

In [12]:
a=a.reshape((3,3),order='c') #! sonr bakalım
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
arr=np.random.randint(1,10,8)
arr

array([6, 3, 2, 8, 4, 6, 5, 8])

In [14]:
arr.reshape((4,2))

array([[6, 3],
       [2, 8],
       [4, 6],
       [5, 8]])

In [15]:
arr.reshape((2,4))

array([[6, 3, 2, 8],
       [4, 6, 5, 8]])

In [16]:
arr.reshape((2,2,2))

array([[[6, 3],
        [2, 8]],

       [[4, 6],
        [5, 8]]])

### bazende  boyut belirtmeyiz ve -1 yazarız

In [20]:
arr.reshape(2,-1)

array([[6, 3, 2, 8],
       [4, 6, 5, 8]])

In [21]:
arr.reshape(2,2,-1)

array([[[6, 3],
        [2, 8]],

       [[4, 6],
        [5, 8]]])

In [22]:
arr.reshape(-1)

array([6, 3, 2, 8, 4, 6, 5, 8])

### bir yöntemimiz daha var numpy.reshape(array_name,new_shape,"c")

In [24]:
np.reshape(arr,(2,2,2))

array([[[6, 3],
        [2, 8]],

       [[4, 6],
        [5, 8]]])

In [25]:
arr

array([6, 3, 2, 8, 4, 6, 5, 8])