#   Slicing dilimleme
## one dimention
### * array_name(start:end:step)
### * array_name[:end] array_name(start:) array_name[:] array_name[::step] 
### if it's gap for start = 0, end = sizeofarray-1,  step = 1  

## multi dimention
### same logic just you do it dimention time with seperation them comma
### * matris[start:end:step , start:end:step]

In [13]:
import numpy as np
matris=np.random.randint(0,100,size=(4,4))
print(matris[:,:])#yani hocam C'deki gibi [][] ifadesiyle ulaşmak yok [,] kullanmallıyız
print(matris[0::3,0::3])
print(matris[0,0])
matris[1:3,1:3]

[[94  8 61 33]
 [12 15 64 98]
 [ 9 61 15 76]
 [96 48 92  2]]
[[94 33]
 [96  2]]
94


array([[15, 64],
       [61, 15]])