# sort(array)

tek boyutlu sort(array_name)

matris  sort(array_name,axis)

Not: fonksiyonalrı oop mantiğiyla arr.function() diyed çalıştırabilyorduk, np.function() diye de çalıştırabiliyorduk.

farko oop mantiği ile çalıştırdığında atama yapmasanda değişiklikten etkilernir. diğeri ise (kütüphaneyle çağırma) 

fonksiyonel programlama mantığıyla çalılşır. atama yapmassan etkilenmez :))

In [6]:
import numpy as np
ar=np.random.randint(0,10,5)
ar

array([9, 0, 4, 7, 9])

In [10]:
np.sort(ar)
ar
ar.sort() # dikkat edelim biri metod biri function.

In [23]:
ar2=np.random.randint(10,20,5)
ar3=np.random.randint(5,15,5)
arr=np.concatenate([ar,ar2,ar3])
arr=np.reshape(arr,(3,5))
print(arr[:][:])
arr.sort(axis=1)
arr

[[ 0  4  7  9  9]
 [14 14 14 16 12]
 [ 8 12  9 12  6]]


array([[ 0,  4,  7,  9,  9],
       [12, 14, 14, 14, 16],
       [ 6,  8,  9, 12, 12]])