# split() fuction

arrayleri ayırır.

**numpy.siplit(array,[indis ])**

numpy.vsplit(matris,[inis ]) vertical diviser (according to row indis)


numpy.hsplit(matris,[indis ]) horizontal diviser (according to column indis)

In [25]:
import numpy as np

In [26]:
a=[1,2,3,4,5] #hocam bu bir liste erkan bu pastaa 😅
ar=np.array([6,7,8,9]) #bu ise numpy array netleşti mi :)

In [27]:
ara=np.concatenate((a,ar)) # bu ne şimdi? ayırmadık. öyle havalı olsun diye yaptım bunun ayırmayla alakası yok :))
ara

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
array=np.split(ara,[1,4])
array

[array([1]), array([2, 3, 4]), array([5, 6, 7, 8, 9])]

In [29]:
array2=np.split(a,[2])
array2

[array([1, 2]), array([3, 4, 5])]

In [30]:
array3=np.split(ara,[1,3,5,7])
array3

[array([1]), array([2, 3]), array([4, 5]), array([6, 7]), array([8, 9])]

## vsplit(matris_name,[indis ])

In [31]:
x=np.array([[1,2,3,],[4,5,6],[7,8,9],[10,11,12]])
x

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [32]:
x.ndim
x.shape

(4, 3)

In [33]:
y,z=np.vsplit(x,[2])

In [34]:

z,y

(array([[ 7,  8,  9],
        [10, 11, 12]]),
 array([[1, 2, 3],
        [4, 5, 6]]))

In [10]:
mat=np.array([[1,2,3],[4,5,6]])
m,t=np.vsplit(mat,[1])
a1=t
a2=m

In [35]:
mat=np.concatenate([a1,a2],axis=0)
mat #done :))

array([[4, 5, 6],
       [1, 2, 3]])

## hsplit(array,[indis ])

* örnek matris  [[a][b][c][d]]  şeklinde olsun bunu  [[d]][b][c][a]] şekline çevirelim
             
bu horizontal bolme olmadı. o zaman 

* ornek2 [[1,2,3],[4,5,6],[7,8,9]] matrisini [[1,4,7],[2,5,8],[9,6,3]] şekline getirelim. determinant yani :))
              

In [36]:
matris=np.array([[1,2],[3,4]])
                                        

In [37]:
ma1,ma2=np.vsplit(matris,[1])
ma1=np.reshape(ma1,(-1))
ma2=np.reshape(ma2,(-1))
ma1a,ma1b=np.split(ma1,[1])
ma2a,ma2b=np.split(ma2,[1])
ma1=np.concatenate([ma2b,ma1b])
ma2=np.concatenate([ma2a,ma1a])
mat=np.concatenate([ma1,ma2])
matris=np.reshape(mat,(2,2))
matris

array([[4, 2],
       [3, 1]])

In [43]:
or2=np.array([[1,2,3],[4,5,6],[7,8,9]])
or2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [44]:
or2a,or2b,or2c=np.hsplit(or2,[1,2])
or2a=np.reshape(or2a,(1,3))
or2b=np.reshape(or2b,(1,3))
or2c=np.reshape(or2c,(1,3))

In [45]:
or2=np.concatenate([or2a,or2b,or2c],axis=0) #congratulations dear :))
or2

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])