### * proccesing submatris 
### * hadle submtris 
### * copy method

copy metodu kullanırsak yapılan değişikliklerden ana matris etkilenmez.

In [42]:
import numpy as np
matris=np.random.randint(10,100,size=(12,12))
matris

array([[56, 64, 74, 22, 83, 41, 81, 12, 83, 78, 36, 97],
       [42, 63, 64, 28, 18, 49, 32, 31, 78, 94, 37, 80],
       [21, 76, 65, 53, 18, 21, 35, 42, 52, 73, 80, 80],
       [97, 79, 59, 59, 53, 29, 59, 13, 53, 79, 85, 22],
       [37, 21, 97, 99, 74, 20, 53, 56, 75, 81, 77, 48],
       [92, 17, 85, 55, 66, 73, 41, 14, 93, 23, 52, 13],
       [70, 49, 78, 77, 90, 46, 63, 82, 22, 15, 76, 22],
       [11, 90, 40, 69, 70, 23, 21, 74, 76, 96, 50, 86],
       [50, 72, 72, 73, 81, 12, 85, 13, 21, 13, 50, 92],
       [51, 39, 94, 80, 23, 29, 20, 36, 48, 33, 77, 51],
       [45, 35, 11, 91, 92, 64, 19, 14, 89, 84, 95, 79],
       [17, 88, 48, 18, 61, 72, 97, 40, 40, 42, 36, 59]])

In [43]:
core=matris[4:8,4:8]
lTquart=matris[0:4,0:4]
lBquart=matris[8:,0:4]
rTquart=matris[0:4,8:]
rBquart=matris[8:,8:]


In [44]:
lTquart[:,:], lBquart[:,:], rTquart[:,:], rBquart[:,:]=np.zeros((4,4))
core[:,:]=np.zeros((4,4))
matris##todo  işte bu 💪🏻

array([[ 0,  0,  0,  0, 83, 41, 81, 12,  0,  0,  0,  0],
       [ 0,  0,  0,  0, 18, 49, 32, 31,  0,  0,  0,  0],
       [ 0,  0,  0,  0, 18, 21, 35, 42,  0,  0,  0,  0],
       [ 0,  0,  0,  0, 53, 29, 59, 13,  0,  0,  0,  0],
       [37, 21, 97, 99,  0,  0,  0,  0, 75, 81, 77, 48],
       [92, 17, 85, 55,  0,  0,  0,  0, 93, 23, 52, 13],
       [70, 49, 78, 77,  0,  0,  0,  0, 22, 15, 76, 22],
       [11, 90, 40, 69,  0,  0,  0,  0, 76, 96, 50, 86],
       [ 0,  0,  0,  0, 81, 12, 85, 13,  0,  0,  0,  0],
       [ 0,  0,  0,  0, 23, 29, 20, 36,  0,  0,  0,  0],
       [ 0,  0,  0,  0, 92, 64, 19, 14,  0,  0,  0,  0],
       [ 0,  0,  0,  0, 61, 72, 97, 40,  0,  0,  0,  0]])

In [45]:
matris2=np.random.randint(10,100,size=(12,12))
matris2

array([[24, 29, 66, 45, 43, 99, 27, 43, 69, 99, 62, 68],
       [98, 84, 70, 11, 90, 37, 30, 70, 76, 38, 71, 83],
       [67, 35, 92, 60, 52, 83, 73, 13, 86, 42, 22, 32],
       [14, 83, 57, 13, 20, 19, 82, 40, 19, 76, 27, 43],
       [70, 18, 39, 94, 51, 15, 51, 18, 92, 88, 71, 49],
       [81, 54, 61, 52, 80, 96, 38, 17, 54, 94, 83, 32],
       [64, 46, 99, 38, 93, 72, 84, 66, 56, 62, 69, 63],
       [69, 25, 70, 18, 93, 90, 63, 99, 49, 80, 43, 86],
       [51, 76, 77, 92, 75, 48, 80, 79, 58, 12, 70, 11],
       [47, 82, 57, 77, 80, 87, 65, 65, 35, 30, 10, 78],
       [22, 59, 36, 23, 33, 71, 56, 78, 99, 22, 75, 14],
       [77, 32, 37, 35, 41, 38, 93, 65, 97, 94, 57, 86]])

In [46]:
core2=matris2[4:8,4:8].copy
lTquart2=matris2[0:4,0:4].copy
lBquart2=matris2[8:,0:4].copy
rTquart2=matris2[0:4,8:].copy
rBquart2=matris2[8:,8:].copy

In [47]:
lTquart[:,:], lBquart[:,:], rTquart[:,:], rBquart[:,:]=np.zeros((4,4))
core[:,:]=np.zeros((4,4))
matris2

array([[24, 29, 66, 45, 43, 99, 27, 43, 69, 99, 62, 68],
       [98, 84, 70, 11, 90, 37, 30, 70, 76, 38, 71, 83],
       [67, 35, 92, 60, 52, 83, 73, 13, 86, 42, 22, 32],
       [14, 83, 57, 13, 20, 19, 82, 40, 19, 76, 27, 43],
       [70, 18, 39, 94, 51, 15, 51, 18, 92, 88, 71, 49],
       [81, 54, 61, 52, 80, 96, 38, 17, 54, 94, 83, 32],
       [64, 46, 99, 38, 93, 72, 84, 66, 56, 62, 69, 63],
       [69, 25, 70, 18, 93, 90, 63, 99, 49, 80, 43, 86],
       [51, 76, 77, 92, 75, 48, 80, 79, 58, 12, 70, 11],
       [47, 82, 57, 77, 80, 87, 65, 65, 35, 30, 10, 78],
       [22, 59, 36, 23, 33, 71, 56, 78, 99, 22, 75, 14],
       [77, 32, 37, 35, 41, 38, 93, 65, 97, 94, 57, 86]])