## normalde fonkssiyonlarla yapılan işlemleri matematiksel operatorlerle yapmak mümkün 

In [37]:
import numpy as np
m=np.arange(1,10,1,dtype="int").reshape(3,3)
m

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

**<**      **less() function**

In [9]:
m[m<5]


array([1, 2, 3, 4])

In [10]:
np.less(m,5)

array([[ True,  True,  True],
       [ True, False, False],
       [False, False, False]])

In [11]:
m*10

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [12]:
m

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
m/10

array([[0.1, 0.2, 0.3],
       [0.4, 0.5, 0.6],
       [0.7, 0.8, 0.9]])

In [14]:
m/10+1

array([[1.1, 1.2, 1.3],
       [1.4, 1.5, 1.6],
       [1.7, 1.8, 1.9]])

### pow

In [19]:
np.power(m,2)

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [15]:
m**2

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

### mod

In [17]:
m%2

array([[1, 0, 1],
       [0, 1, 0],
       [1, 0, 1]])

In [18]:
np.mod(m,2)

array([[1, 0, 1],
       [0, 1, 0],
       [1, 0, 1]])

### sonuç: yani operatorlerle yağtığımız bu işlemler aslında arkada ufunc 'ın çalışması sayesinde olur

#### Ek fonksiyonlar

**absolute**

In [20]:
arr=np.random.randint(-100,-1,(3,3))
arr

array([[-76, -15, -90],
       [-23, -95, -90],
       [-25, -79, -67]])

In [22]:
np.absolute(arr)

array([[76, 15, 90],
       [23, 95, 90],
       [25, 79, 67]])

**trigo**

In [23]:
np.sin(arr)

array([[-0.56610764, -0.65028784, -0.89399666],
       [ 0.8462204 , -0.68326171, -0.89399666],
       [ 0.13235175,  0.44411267,  0.85551998]])

In [30]:
a=np.arange(0,91,30).reshape(2,2)
a

array([[ 0, 30],
       [60, 90]])

In [32]:
np.cos(a)

array([[ 1.        ,  0.15425145],
       [-0.95241298, -0.44807362]])

In [31]:
np.sin(a)

array([[ 0.        , -0.98803162],
       [-0.30481062,  0.89399666]])

**logaritma**

In [34]:
l=np.array([[2,4],[8,16],[32,64]])
l

array([[ 2,  4],
       [ 8, 16],
       [32, 64]])

In [35]:
np.log2(l) #:))

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

**kök**

In [36]:
np.sqrt(l)

array([[1.41421356, 2.        ],
       [2.82842712, 4.        ],
       [5.65685425, 8.        ]])